### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by VilDegard** [rulex/rtorrent-pushover#2]
Hi, 

Just wanted to correct the amendment on .rtorrent which is supposed to be:

system.method.set_key = event.download.finished,notificationscript,"execute=bash,home/user/rtorrent-pushover.sh,$d.get_name="
 
notificationscript should be there instead of notify_me.

Now it's working perfectly.
Thanks.

**Comment by rulex** [comment]
I can't really find any documentation about this but I think that string can be anything you want.
